app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Car, car_schema, car_multi_schema, user_schema

api = Blueprint('ap', __name__, url_prefix='/api')

# Add new car endpoint
@api.route('/car', methods = ['POST'])
@token_required
def add_car(current_user_token):
    make = request.json['make']
    model = request.json['model']
    year = request.json['year']
    user_token = current_user_token.token

    print(f'User\'s token: {current_user_token.token}')

    try:
        car = Car(make, model, year, user_token)
        db.session.add(car)
        db.session.commit()

        response = car_schema.dump(car)
        return jsonify(response)
    except:
        return jsonify({'message' : 'Failed to add item'}), 500

# Get all cars added by user
@api.route('/car', methods = ['GET'])
@token_required
def get_car(current_user_token):
    user_token = current_user_token.token
    car = Car.query.filter_by(user_token=user_token).all()
    if car:
        response = car_multi_schema.dump(car)
        return jsonify(response)
    return jsonify({'message' : 'Item not found'}), 404

# Get single car added by user
@api.route('/car/<id>', methods = ['GET'])
@token_required
def get_single_car(current_user_token, id):
    user_token = current_user_token.token
    car = Car.query.filter_by(user_token=user_token, id=id).all()
    if car:
        response = car_schema.dump(car)
        return jsonify(response)
    return jsonify({'message' : 'Item not found'}), 404
    
# Update car endpoint
@api.route('/car/<id>', methods = ['POST','PUT'])
@token_required
def update_car(current_user_token, id):
    user_token = current_user_token.token
    car = Car.query.get(id)
    if car and car.user_token == user_token:
        car.make = request.json['make']
        car.model = request.json['model']
        car.year = request.json['year']
        car.user_token = current_user_token.token

        db.session.commit()
        response = car_schema.dump(car)
        return jsonify(response)
    return jsonify({'message' : 'Item not found'}), 404

# Delete car endpoint
@api.route('/car/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_user_token, id):
    user_token = current_user_token.token
    car = Car.query.get(id)
    if car and car.user_token == user_token:
        db.session.delete(car)
        db.session.commit()
        response = car_schema.dump(car)
        return jsonify(response)
    return jsonify({'message' : 'Item not found'}), 404

# Delete user endpoint
@api.route('/user/<id>', methods = ['DELETE'])
@token_required
def delete_user(current_user_token, id):
    user_token = current_user_token.token
    user = User.query.get(id)
    if user and user.token == user_token:
        db.session.delete(user)
        db.session.commit()
        response = user_schema.dump(user)
        return jsonify(response)
    return jsonify({'message' : 'User not found'}), 404

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully createed a user account {email}', 'User-created')
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data: Please check your form')
    
    return render_template('sign_up.html', form=form)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You have successfully logged in!', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Login failed.', 'auth-failed')
    except:
        raise Exception('Error: please check that your form data is correct')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template
from models import User, Car

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    users = User.query.all()
    return render_template('index.html', users=users)

@site.route('/profile')
def profile():
    user = User.query.all()
    return render_template('profile.html', user=user)

@site.route('/cars')
def cars():
    cars = Car.query.all()
    return render_template('cars.html', cars=cars)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="/static/css/main.css">
<script src="https://kit.fontawesome.com/3ef1af0600.js" crossorigin="anonymous"></script>
<title>Home</title>
</head>
<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg flex-wrap bg-black fixed-top p-0">
        <div class="container mw-100">
            <a href="{{ url_for('site.home') }}" class="navbar-brand text-light d-flex align-items-center">
                <h2 class="m-0">Car Inventory</h2>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu"><i class="fa-solid fa-bars fs-2"></i></button>

            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto mb-3 mb-lg-0">
                    <li class="nav-item text-end">
                        <a href="{{ url_for('site.home') }}" class="nav-link fs-5">Home</a>
                    </li>
                    <li class="nav-item text-end">
                        <a href="{{ url_for('site.cars') }}" class="nav-link fs-5">Cars</a>
                    </li>
                    {% if current_user.is_authenticated  %}
                    <li class="nav-item text-end">
                        <a href="{{ url_for('site.profile') }}" class="nav-link fs-5">Profile</a>
                    </li>
                    <li class="nav-item text-end">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link fs-5">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item text-end">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link fs-5">Sign In</a>
                    </li>
                    <li class="nav-item text-end">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link fs-5">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'Enter your email') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter a password") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2", value = "Submit")}}
</form>